### ISSUE TITLE
BookFields class error after rebuild million times ..as shown

### ISSUE THREAD

**Issue by mohamedebrahim96** [Zhuinden/realm-book-example#11]
![25725725](https://user-images.githubusercontent.com/16405013/29495409-00b58960-85bf-11e7-90b8-3bfdc344417b.JPG)

![52452](https://user-images.githubusercontent.com/16405013/29495414-0a4df278-85bf-11e7-9661-cea25b85eca7.JPG)

**Comment by mohamedebrahim96** [comment]
![257858785875hhhhhhhhhhhhhhhhhhhhhhh](https://user-images.githubusercontent.com/16405013/29495425-2fd1d910-85bf-11e7-9bdc-4e5b8811415e.JPG)

maybe i have forgot some dependencies

**Comment by Zhuinden** [comment]
`__Fields` classes should be generated by `realmfieldnameshelper` on `rebuild`.

If they don't get generated, that might mean you have an unrelated compilation error elsewhere
