### ISSUE TITLE
BookFields class is missing in repository

### ISSUE THREAD

**Issue by devqualwebs** [Zhuinden/realm-book-example#4]
Hey 
can you please update your repository and add BookFields.java  in the
[ app/src/main/java/com/zhuinden/realmbookexample/data/entity]

**Comment by Zhuinden** [comment]
It's automatically generated when you press Rebuild

**Comment by devqualwebs** [comment]
thanks

**Comment by devqualwebs** [comment]
How that class generated automatically 
How can I do the same for my feilds

**Comment by Zhuinden** [comment]
It comes from [this](https://github.com/cmelchior/realmfieldnameshelper)

```
compile 'dk.ilios:realmfieldnameshelper:1.0.0'
```

Which relies on APT:

```
    classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
```

and

```
apply plugin: 'com.neenbedankt.android-apt' 
```

**Comment by devqualwebs** [comment]
Thank you 

that helps alot
