### ISSUE TITLE
Open source license?

### ISSUE THREAD

**Issue by ChrisGaddes** [Zhuinden/realm-book-example#6]
Thank for this fantastic resource! Do you mind if I use a clone of this example as a basis for an application I'm developing? I couldn't find anything about you releasing it under a particular license.

Thanks!

**Comment by Zhuinden** [comment]
Ah, yeah, I never included a license -  but sure, nothing in this code is secret :) it was written as the remake of a tutorial. There's no point to a tutorial you cannot actually use, right?

**Comment by ChrisGaddes** [comment]
Awesome, thanks so much!! I agree, but I wanted to make sure. Thanks again!

**Comment by Zhuinden** [comment]
added "do whatever you want with it" license txt
